### ISSUE TITLE
Bug when starting a service with name that is the start of an already running service

### ISSUE THREAD

**Issue by liquidarmour** [hmrc/service-manager#29]
The latest release has introduced a problem that means a service will fail to start if there is a service whose name starts with the new services name.

EG. If you have 2 services GG and GG_STUBS and you declare them in a profile as 
```
GG_STUBS GG
```
then GG will fail to start. 

Switching the order and both will start.

**Comment by duncancrawford** [comment]
@agilestevesmith, @charleskubicek & @HolyHaddock please can you look at this or get someone to look this today?

@liquidarmour

**Comment by HolyHaddock** [comment]
Already looking at it.

**Comment by duncancrawford** [comment]
Cool, do we have a fix? (I am only the messenger btw)

**Comment by vaughansharman** [comment]
Im sure Mark is on this but a couple of suggestions in the meantime

You can manually install the previous version if this is affecting you:
pip install servicemanager==0.0.23

Another suggestion is perhaps there is an issue (or an improvement you can make) with the regex in your services.json file...

**Comment by HolyHaddock** [comment]
The patterns for JVM services are generated from the service name, which I think is something it would be good to keep.

My first stab at a fix turns out to have some issues.
