### ISSUE TITLE
travis build checks report success but build is broken

### ISSUE THREAD

**Issue by vaughansharman** [hmrc/service-manager#40]
See details of build on github, github reports everything green, but if you look deeper you can see the following (and more) failing...

test/tests.py:42: TestFileServer.test_file_server PASSED
test/tests.py:84: TestNexus.test_nexus_tgz FAILED
test/tests.py:64: TestNexus.test_nexus_zip FAILED

**Comment by jakobgrunig** [comment]
This is now working
