### ISSUE TITLE
With Ubuntu 17.04 and systemd, --stop of a JVM process kills my desktop session

### ISSUE THREAD

**Issue by lutnos** [hmrc/service-manager#70]
Since upgrading to Ubuntu 17.04, an `sm --stop` of a JVM process kills my desktop session.

This appears to because where as previously, the ppid was a Session Init /sbin/upstart, now it is a user mode /bin/systemd .

Presumably, sending a SIGINT to upstart was benign, sending it to systemd is catastrophic - it treats it as SIGTERM.

As a workaround, https://github.com/lutnos/service-manager/commit/aa44f6077121a10692dba885c84b1a8efeecfd70, I am no longer killing the ppid, but I am not at all clear in which environments this is or was necessary.

ATB

**Comment by daniel-manning** [comment]
I looked at a work around based on an earlier commit to not kill systemd (https://github.com/daniel-manning/service-manager/commit/37f2b23f50eb9aca62e51ed2514a8c913c9ef8d1) but it didn't fix several tests which fail when run on 17.04. Referencing here in case it is useful to anyone investigating.

**Comment by lutnos** [comment]
I've now raised https://github.com/hmrc/service-manager/pull/71 .

Quick tests pass, that is:

`py.test -v -m 'not online' -s test/`

Full tests haven't passed in Travis since PR 54, it appears :-(

**Comment by jakobgrunig** [comment]
Closing as #71 was merged
