### ISSUE TITLE
SM should handle both artifacts repo without need for additional configuration

### ISSUE THREAD

**Issue by codesurf42** [hmrc/service-manager#80]
sm would be easier to use and could save developers time if there was no need to specify explicitly which repository (nexus, bintray, anything else...) should be tried to download specific artifact.
For now this has to be configured by flag in services.json config.

Having such feature would prevent issues like https://github.com/hmrc/service-manager/issues/79 from happening and improve operational reliability and agility of MDTP platform.

**Comment by jakobgrunig** [comment]
I agree... 
This has been implemented by adding a `binary.repo` property. 
https://github.com/hmrc/service-manager/blob/master/servicemanager/smartifactrepofactory.py#L12-L20
The old logic, looking for the existence of the `nexus` property has been discarded.
This has been released with servicemanager version 1.4.0
