### ISSUE TITLE
Package claim on PyPI

### ISSUE THREAD

**Issue by di** [hmrc/service-manager#85]
Per https://github.com/pypa/warehouse/issues/3938, can a owner of this repository confirm that the user https://pypi.org/user/hmrc-web-operations/ should be transferred to one of the two addresses listed there (and thus, the ownership of the `servicemanager` project as well)?

Thanks!

**Comment by andysingleton** [comment]
Hi di. Confirming we are owners of this project (i.e. members of the hmrc organisation.)

**Comment by reeshishah** [comment]
Hi Di, I also confirm the above. Thank you

**Comment by jakobgrunig** [comment]
Hi di. I can confirm that both Andy and Reeshi are owners of the service-manager project.

**Comment by di** [comment]
Thanks!
